name: CI

on:
  pull_request:
    branches: [ "main", "dev" ]
  push:
    branches: [ "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
      - name: Unit Tests
        run: pnpm test --filter=!web
      - name: Build web
        run: pnpm --filter web build
